# Generated by Django 3.0.4 on 2020-04-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=30)),
                ('credit', models.CharField(max_length=10)),
                ('etc', models.CharField(max_length=200)),
            ],
        ),
    ]
