# Generated by Django 3.0.5 on 2020-05-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_auto_20200516_0225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Substitute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=20)),
                ('course_title', models.CharField(max_length=20)),
                ('sub_id', models.CharField(max_length=20)),
                ('sub_title', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
    ]
