# Generated by Django 3.0.5 on 2020-05-16 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0006_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
