# Generated by Django 3.0.5 on 2020-05-22 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0014_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
