# Generated by Django 3.0.5 on 2020-05-22 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0016_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
