# Generated by Django 3.0.5 on 2020-06-02 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0018_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
